package types

import (
	"encoding/json"
	"strings"
)

// Channel represents a notification delivery channel configuration.
type Channel struct {
	// ID is a stable UUID auto-generated by the API on creation/update.
	// Used to uniquely identify channels within the JSONB array for atomic updates
	// (e.g., secret rotation via UpdateChannelConfig). Format: UUID v4.
	ID      string         `json:"id"`
	Type    ChannelType    `json:"type"`
	Config  map[string]any `json:"config"`
	Enabled bool           `json:"enabled"`
}

// ChannelList is a slice of Channel.
type ChannelList []Channel

// MarshalJSON implements custom JSON marshaling that redacts sensitive config values.
// This prevents secret leakage in API responses.
func (c Channel) MarshalJSON() ([]byte, error) {
	type Alias Channel
	safe := Alias(c)
	if safe.Config != nil {
		redacted := make(map[string]any)
		for k, v := range c.Config {
			if isSensitive(k) {
				redacted[k] = "[REDACTED]"
			} else {
				redacted[k] = v
			}
		}
		safe.Config = redacted
	}
	return json.Marshal(safe)
}

// isSensitive returns true if the config key holds a secret value.
func isSensitive(key string) bool {
	k := strings.ToLower(key)
	return k == "secret" || k == "password" || strings.Contains(k, "key")
}
