-- 003_watchpoints.up.sql
-- Create the watchpoints table with spatial sharding, mode exclusivity, and batcher-optimized indexes.

CREATE TABLE watchpoints (
    id                    TEXT PRIMARY KEY DEFAULT 'wp_' || gen_random_uuid()::text,
    organization_id       TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    -- Identity & Location
    name                  VARCHAR(200),
    location_lat          DOUBLE PRECISION NOT NULL CHECK (location_lat BETWEEN -90 AND 90),
    location_lon          DOUBLE PRECISION NOT NULL CHECK (location_lon BETWEEN -180 AND 180),
    location_display_name VARCHAR(200),
    timezone              VARCHAR(50) NOT NULL,

    -- Spatial Sharding (Deterministic Tile ID)
    -- Generates "lat_index.lon_index" for 22.5x45 degree tiles
    tile_id TEXT GENERATED ALWAYS AS (
        CONCAT(
            FLOOR((90.0 - location_lat) / 22.5)::INT,
            '.',
            FLOOR(
                CASE
                    WHEN location_lon >= 0 THEN location_lon
                    ELSE 360.0 + location_lon
                END / 45.0
            )::INT
        )
    ) STORED,

    -- Mode Configuration (Mutually Exclusive)
    time_window_start     TIMESTAMPTZ, -- Nullable for Monitor Mode
    time_window_end       TIMESTAMPTZ,
    monitor_config        JSONB,       -- Nullable for Event Mode

    -- Logic & Delivery
    conditions            JSONB NOT NULL, -- Array of Condition objects
    condition_logic       VARCHAR(10) NOT NULL DEFAULT 'ALL' CHECK (condition_logic IN ('ANY', 'ALL')),
    channels              JSONB NOT NULL, -- Array of Channel objects
    preferences           JSONB,
    template_set          VARCHAR(50) DEFAULT 'default',

    -- Meta
    status                VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'archived')),
    test_mode             BOOLEAN NOT NULL DEFAULT FALSE,
    tags                  TEXT[],
    config_version        INTEGER NOT NULL DEFAULT 1, -- Increments on logic change
    source                VARCHAR(100),

    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    archived_at           TIMESTAMPTZ,
    archived_reason       VARCHAR(50),
    deleted_at            TIMESTAMPTZ, -- Soft delete

    -- Pause reason: Distinguishes user pauses from billing enforcements.
    paused_reason         VARCHAR(50),

    -- Post-Event Summary: Stores the accuracy report (Predicted vs Actual)
    -- generated by the Eval Worker upon archival. See OBS-007.
    summary               JSONB,

    -- Constraint: Enforce Mode Exclusivity
    CONSTRAINT valid_mode CHECK (
        (time_window_start IS NOT NULL AND time_window_end IS NOT NULL AND monitor_config IS NULL)
        OR
        (time_window_start IS NULL AND time_window_end IS NULL AND monitor_config IS NOT NULL)
    )
);

-- =============================================================================
-- Indexes
-- =============================================================================

-- 1. Batcher Query (Index-Only Scan): Critical for performance.
--    Must exclude soft-deleted items.
CREATE INDEX idx_watchpoints_tile_active ON watchpoints(tile_id, status)
WHERE status = 'active' AND deleted_at IS NULL;

-- 2. Geospatial Lookup
CREATE INDEX idx_watchpoints_location ON watchpoints USING GIST (ll_to_earth(location_lat, location_lon));

-- 3. Dashboard/List Views
CREATE INDEX idx_watchpoints_org_status_test ON watchpoints(organization_id, status, test_mode)
WHERE deleted_at IS NULL;

-- 4. Tag Filtering
CREATE INDEX idx_watchpoints_tags ON watchpoints USING GIN (tags);

-- 5. Archival Cleanup
CREATE INDEX idx_watchpoints_archived ON watchpoints(archived_at) WHERE status = 'archived';
